webdice_web/__init__.py
import glob
import os
from itertools import groupby
from flask import Flask
from flask.ext.assets import Environment, Bundle
from flask import render_template
from webdice_web.constants import BASE_DIR
# from flask_restful import Api, reqparse

session_opts = {
    'session.type': 'ext:memcached',
    'session.cookie_expires': True,
    'session.lock_dir': './data',
    'session.url': '127.0.0.1:11211',
    'session.memcache_module': 'pylibmc',
    'session.auto': True
}

app = Flask(__name__)
app.config.from_object('config')
# api = Api(app)
# api_parser = reqparse.RequestParser()
app.config['DEBUG'] = True
app.config['SECRET_KEY'] = 'Ad78gii#$3979oklaklf'


@app.errorhandler(404)
def not_found(error):
    return render_template('errors/404.html'), 404


@app.errorhandler(403)
def not_found(error):
    return render_template('errors/403.html'), 403


@app.errorhandler(500)
def not_found(error):
    return render_template('errors/50x.html'), 500


@app.context_processor
def context_globals():
    return dict()

@app.context_processor
def glossary_terms():
    return dict(
        glossary_terms=[list(g) for k, g in groupby(map(
            lambda x: ''.join(x.split('/')[-1].split('.')[:-1]),
            sorted(glob.glob(os.path.join(
                BASE_DIR, 'templates', 'modules', 'glossary', 'terms',
                '*.html')))), key=lambda x: x[0])],
        advanced_glossary_terms=map(
            lambda x: ''.join(x.split('/')[-1].split('.')[:-1]),
            sorted(glob.glob(os.path.join(
                BASE_DIR, 'templates', 'modules', 'glossary', 'terms',
                'advanced', '*.html')))),
    )


from webdice_web.views import mod as work_module
app.register_blueprint(work_module)


assets = Environment(app)
js = Bundle('js/stacked_chart.js',
            'js/webdice_zoom.js',
            'js/webdice_param_eq.js',
            'js/webdice_download_svg.js',
            'js/webdice_download_csv.js',
            'js/main.js',
            'js/webdice_range_slider.js',
            'js/webdice_tabs.js',
            filters='jsmin', output='gen/webdice.js')
assets.register('js_webdice', js)
js = Bundle('js/vendor/d3.v3.min.js', 'js/vendor/json2.js',
            'js/vendor/modernizr.custom.27311.js',
            filters='jsmin', output='gen/vendor.js')
assets.register('js_vendor', js)
js = Bundle('js/vendor/fd-slider.min.js',
            filters='jsmin', output='gen/fd-slider.js')
assets.register('js_slider', js)
css = Bundle('css/main.css', 'css/fd-slider.min.css',
            filters='cssmin', output='gen/main.css')
assets.register('css_main', css)


if __name__ == '__main__':
    app.run()

webdice_web/views.py
from __future__ import division
import json
import zipfile
import csv
import StringIO
import os
from numpy import inf
from lxml import etree
from flask import render_template, request, Blueprint, jsonify, send_file
from webdice.dice import Dice2010
from webdice_web.constants import BASE_DIR


mod = Blueprint('webdice', __name__, static_folder='static',
                template_folder='templates')


def validate_number(n):
    """Currently unused. This is a stub for number validation
    before passing values to the Dice2007 object."""
    try: float(n)
    except ValueError: raise Exception('Input needs to be a number.')
    else: return n


def run_loop(form):

    dice = Dice2010()

    for field in ['e2050', 'e2100', 'e2150']:
        form[field] = float(form[field]) / 100

    for field in ['p2050', 'p2100', 'p2150']:
        form[field] = float(form[field]) / 100

    for p in dice.user_params:
        try:
            setattr(dice.params, p, float(form[p]))
        except KeyError:
            pass
        except ValueError:
            pass

    dice.params.productivity_model = 'dice_backstop_2013'

    try:
        dice.params.carbon_model = form['carbon_model']
        dice.params.damages_model = form['damages_model']
    except KeyError:
        dice.params.carbon_model = 'dice_2010'
        dice.params.damages_model = 'dice_2010'

    opt = False
    dice.params.treaty = False
    dice.params.carbon_tax = False
    policy = form['policy_type']
    if policy == 'treaty':
        dice.params.treaty = True
    elif policy == 'optimized':
        opt = True
    elif policy == 'carbon_tax':
        dice.params.carbon_tax = True
    dice.loop(opt=opt)
    out = dice.format_output()
    out['data'] = {
        k: [l if l > -inf else -999 for l in v] for k, v in out['data'].iteritems()
    }
    out['data']['discount_rate'][0] = None
    out['data']['discount_forward'][0] = None
    return jsonify(**out)


@mod.route('/')
def index():
    """Returns index page."""
    return render_template(
        'index.html',
    )


@mod.route('/documentation')
def documentation():
    """Returns index page."""
    return render_template(
        'modules/documentation/index.html',
    )


@mod.route('/glossary')
def glossary():
    """Returns index page."""
    return render_template(
        'modules/glossary/index.html',
    )


@mod.route('/glossary/<term>')
def glossary_term(term):
    """Returns index page."""
    return render_template(
        'modules/glossary/static_page.html',
        term=term
    )


@mod.route('/glossary/advanced/<term>')
def glossary_advanced_term(term):
    """Returns index page."""
    s = ''
    f = os.path.join(BASE_DIR, 'templates', 'modules', 'glossary', 'terms',
                     'advanced', '{}.html'.format(term))
    with open(f) as f:
        s = f.read()
    return s


@mod.route('/advanced')
def advanced():
    return render_template(
        'versions/advanced.html',
        dice_version=2010,
    )


@mod.route('/standard')
def standard():
    return render_template(
        'versions/standard.html',
    )


@mod.route('/run/standard', methods=['POST', 'GET'])
def graphs_standard():
    form = json.loads(request.data)
    new_data = {
        'temp_co2_doubling': [1, 2, 3.2, 4, 5],
        'damages_exponent': [1, 1.4, 2.0, 2.8, 4.0],
        'productivity_decline': [.015, .011, .009, .003, 0.0],
        'backstop_decline': [0.20, 0.10, 0.05, 0.025, 0.0],
        'intensity_decline_rate': [.060, .02, .006, .0006, 0.0],
    }
    for field in new_data.keys():
        try:
            if form[field]:
                form[field] = new_data[field][int(form[field]) - 1]
        except KeyError:
            pass

    for field in ['depreciation', 'savings', 'prstp', 'prod_frac', ]:
        try:
            if form[field]:
                form[field] = float(form[field]) / 100
        except KeyError:
            pass

    return run_loop(form)


@mod.route('/run/advanced', methods=['POST', 'GET'])
def graphs_advanced():
    """
    Get data from <form>, run DICE loop.
    ...
    Args:
        None
    Returns:
        Formatted step values
    """
    form = json.loads(request.data)
    for field in ['depreciation', 'savings', 'prstp', 'backstop_decline',
                  'productivity_decline', 'intensity_decline_rate',
                  'prod_frac', ]:
        try:
            if form[field]:
                form[field] = float(form[field]) / 100
        except KeyError:
            pass

    return run_loop(form)


@mod.route('/get_svg', methods=['POST', ])
def get_svg():
    def combine_custom(c, t):
        ns = 'http://www.w3.org/2000/svg'
        c = etree.fromstring(c)
        t = etree.fromstring(t)
        cg = c.xpath('/n:svg/n:g', namespaces={'n': ns})
        tg = t.xpath('/n:svg/n:g', namespaces={'n': ns})
        tgg = tg[1].xpath('./n:g', namespaces={'n': ns})
        c.append(tg[0])
        for t in tgg:
            cg[1].append(t)
        return etree.tostring(c)
    form = request.form
    buffer = StringIO.StringIO()
    zipped = zipfile.ZipFile(buffer, 'w')
    for k in form.keys():
        s = StringIO.StringIO()
        if k == 'custom_graph':
            s.write(combine_custom(str(form['custom_graph']),
                                   str(form['twin_graph'])))
        else:
            s.write(str(form[k]))
        zipped.writestr('{}.svg'.format(k), s.getvalue())
    zipped.close()
    buffer.seek(0)
    return send_file(buffer,
                     attachment_filename='{}.zip'.format('WebDICE-SVGs'),
                     as_attachment=True)


@mod.route('/get_csv', methods=['POST',])
def get_csv():
    buffer = StringIO.StringIO()
    data = json.loads(request.form['data'])
    writer = csv.writer(buffer)
    for run in data.keys():
        writer.writerow([data[run]['name']])
        writer.writerow(data[run]['parameters'].keys())
        writer.writerow(data[run]['parameters'].values())
        for var in data[run]['data'].keys():
            writer.writerow([var] + data[run]['data'][var])
    buffer.seek(0)
    return send_file(buffer,
                     attachment_filename='{}.csv'.format('WebDICE-CSV'),
                     as_attachment=True)

webdice_web/templates/_macros.html
{% macro render_menu(version) %}
  <li><h1><a href="{{ url_for('webdice.index') }}">webDICE</a></h1></li>
  <li{% if version == 'standard' %} class=active{% endif %}>
    <a href="{{ url_for('webdice.standard') }}">Standard</a></li>
  <li id=advanced_pages{% if version == 'advanced' %} class=active{% endif %}>
    <a href="{{ url_for('webdice.advanced') }}">Advanced</a></li>
  <li{% if version == 'documentation' %} class=active{% endif %}>
    <a href={{ url_for('webdice.documentation') }}>Documentation</a></li>
{% endmacro %}

webdice_web/templates/advanced_2010.html
{% extends 'advanced_2007.html' %}
{% block parameters %}
{% include 'modules/parameters_2010.html' %}
{% endblock %}

webdice_web/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>RDCEP | webDICE</title>
  {% assets 'css_main' %}
  <link rel="stylesheet" href="{{ ASSET_URL }}" media="screen" title="Default Stylesheet">
  {% endassets %}
  {% assets 'js_vendor' %}
      <script src=//cdnjs.cloudflare.com/ajax/libs/json2/20130526/json2.min.js></script>
      <script src=//cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.min.js></script>
      <script src=//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.min.js></script>
      <script>(window.d3 && window.JSON && window.Modernizr) || document.write('<script src="{{ ASSET_URL }}">\x3C/script>')</script>
    {% endassets %}
  <link rel=icon href={{ url_for('webdice.static', filename='images/brand/rdcep_logo_16.png') }}>
  {% block headcss %}{% endblock %}
  {% block headjs %}{% endblock %}
</head>
<body>
  <!--[if lt IE 7]>
  <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->
  <div id=wrapper>
  {% block page %}{% endblock %}
  {% block footer %}{% endblock %}
  <div id=modal_screen class="modal visuallyhidden"></div>
  <div id=modal_wrap class="modal visuallyhidden">
    <div id=modal_dialogue class="modal visuallyhidden">
      <h2>Warning</h2>
      <p>The parameters you chose produce a result that is physically
        impossible. This can occur because climate change causes harms
        that are sufficiently bad that the economy is forced to operate
        below subsistence levels. It may also occur because you have
        specified emissions reductions that are greater than the emissions
        from the participating countries. webDICE does not contain the
        flexibility to predict what might happen as we approach these
        circumstances so it continues to produce the graphs under the
        parameters you chose.</p>
      <p>Although the results are not physically possible, it does not mean
        that they are not meaningful. webDICE is telling you that under the
        parameter choices you made, something very extreme will happen:
        the population will have to shrink because the economy cannot support
        the full population, or the emissions reductions cannot be achieved
        with the participation rates. The particular results in the graphs,
        however, are not meaningful.</p>
      <p><em>Click this dialogue to dismiss it.</em></p>
    </div>
  </div>
  </div>
</body>
</html>

webdice_web/templates/base_page.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% block headjs -%}
  <script type="text/javascript">
    Options = window.Options || { };
    Options.runs = {};
    Options.dice_version = {% if dice_version %}{{ dice_version|safe }}{% else %}2010{% endif %};
  </script>
{%- endblock %}

{% block page %}
  <header id=main_nav>

    <nav>
      <ul id=top_nav class="clearfix">
        {% block main_menu %}
        {{ macros.render_menu() }}
        {% endblock %}
      </ul>
    </nav>

    <div id=title_legend_wrap>
      <div id=title_legend>
      {% block title_tabs %}
      {% endblock %}
      </div>
    </div>

  </header>

  <article id=main_content class=clearfix>
  {% block content %}
  {% endblock %}
  </article>

  <div id=tool_tip></div>


  <div id=footer_wrap>
    <footer id=main_footer class=clearfix>
      <div id=footer_logo>
        <a href="https://www.rdcep.org/">
          <img src="{{ url_for('webdice.static', filename='images/brand/rdcep_logo_60.png') }}" alt>
        </a>
      </div>
      <div id=footer_attribution>
        <h2><a href="https://www.rdcep.org/">RDCEP</a></h2>
        <p>webDICE is built and maintained by the Center for
          Robust Decision Making on Climate and Energy Policy at the University
          of Chicago. Questions and comments should be directed to
          <a href=mailto:info-rdcep@ci.uchicago.edu>info-rdcep@ci.uchicago.edu</a>.
          </p>
        <p>Funded under NSF Decision Making Under Uncertainty Program.
          Award No. 0951576</p>
      </div>
    </footer>
  </div>

  {% block bodyjs %}
    {% assets 'js_slider', 'js_webdice' %}
    <script src={{ ASSET_URL }}></script>
    {% endassets %}
  {% endblock %}

{% endblock %}

webdice_web/templates/index.html
{% extends 'base_page.html' %}
{% block title_tabs %}{% endblock %}
{% block content %}
  <div id=text_wrap>
    <div id=text_bkgd></div>
    <div class="pane half">
      <h3>About</h3>
      <p>The DICE 2010 model, developed by Professor William Nordhaus of Yale
        University, is the most widely used model of the economics of climate
        change.  webDICE is an online simulation of this model which allows users
        to see the effects of climate change on the economy and society.</p>
      <p>The default values in the model only present the user with one set of
        projected potential impacts.  In order to understand the range of
        potential impacts as a result of climate change, the user can adjust
        parameters within the model to reflect differing beliefs about climate,
        the economy and the future. </p>
      <h3>Contact</h3>
      <p>This model has been developed by researchers at the University of
        Chicago supported by RDCEP.  We are continually working to improve the
        model and the interface. If you have suggestions, contact us at:
        <a href="mailto:info-rdcep@ci.uchicago.edu">info-rdcep@ci.uchicago.edu</a></p>
    </div>
    <div class="pane half">
      <h3><a class="block blue" href="{{ url_for('webdice.standard') }}">Standard inputs</a></h3>
      <p>The standard inputs section is designed for students and new users.
        By limiting the set of adjustable variables to those deemed most
        important, users can view the predicted effects of their beliefs about
        the climate, the economy and the future.</p>
      <h3><a class="block vermilion" href={{ url_for('webdice.advanced') }}>Advanced inputs</a></h3>
      <p>The advanced inputs section is designed for more experienced users.
        The complete set of adjustable variables has been made available,
        allowing the user to assess the effect their beliefs have on the model.</p>
    </div>
  </div>
{% endblock %}
{% block bodyjs %}{% endblock %}

webdice_web/templates/modules/documentation/index.html
{% extends 'base_page.html' %}
{% import '_macros.html' as macros %}

{% block main_menu %}
{{ macros.render_menu('documentation') }}
{% endblock %}

{% block content %}
  <div id=text_wrap>
    <div id=text_bkgd></div>
    <div class="pane half">

      <h3>Documentation</h3>
      <p>webDICE has been thoroughly documented, and varying degrees of
        information are available on this page. If you have
        questions that aren’t answered in our documentation, or if you
        have suggestions, please contact us at
        <a href=mailto:info-rdcep@ci.uchicago.edu>info-rdcep@ci.uchicago.edu</a>.

      <h3><a href=http://github.com/RDCEP/chicagowebdice class="block orange">Source code</a></h3>
      <p>All of the source code for webDICE is available through
        <a href=http://github.com/RDCEP/chicagowebdice>github.com</a>.
        The repo contains both the web frontend, and the python that drives
        the backend.</p>

    </div>
    <div class="pane half">

      <h3><a href="{{ url_for('webdice.glossary') }}" class="block blue">
        Glossary</a></h3>
      <p>Our <a href="{{ url_for('webdice.glossary') }}">online glossary</a>
        provides background and technical information
        about terms and jargon necessary used the site.</p>

      <h3><a href="{{ url_for('webdice.static', filename='docs/Equations_141227.pdf') }}"
             class="block sky-blue">Equations &amp; parameters</a></h3>
      <p>Information about the equations and parameters that underlie
        the model can be found by clicking the link above, or by navigating
        here: <a href="{{ url_for('webdice.static', filename='docs/Equations_141227.pdf') }}">
        {{ url_for('webdice.static', filename='docs/Equations_141227.pdf') }}</a>.</p>

    </div>
  </div>
{% endblock %}

webdice_web/templates/modules/glossary/index.html
{% extends 'base_page.html' %}
{% import '_macros.html' as macros %}

{% block main_menu %}
{{ macros.render_menu('documentation') }}
{% endblock %}

{% block headcss %}
<style>
  #main_content { height: auto; max-height: none; }
  #text_wrap {position: relative; top: auto; margin-top: 6em}
</style>
{% endblock %}
{% block headjs %}
<script type="text/javascript"
{#  src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">#}
  src="{{ url_for('webdice.static', filename='js/vendor/MathJax-2.4/MathJax.js') }}?config=TeX-AMS-MML_HTMLorMML">
</script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({tex2jax: {inlineMath: [['$', '$'], ['\\(', '\\)']]} });
</script>
{% endblock %}

{% block title_tabs %}
  <ul id=alpha_links class=tabs>
    {% for alpha in glossary_terms %}
    <li class=glossary>
      <a href=#section_{{ alpha[0][0] }} data-scroll-object=section_{{ alpha[0][0] }}>
      {{ alpha[0][0]|capitalize }}
      </a>
    </li>
    {% endfor %}
  </ul>
{% endblock %}

{% block content %}
  <div id=text_wrap class=clearfix>
    <div id=text_bkgd></div>
    <div class="pane one-third"></div>
    <div class="pane two-thirds" id=glossary>
    {% block glossary_list %}
      {% for alpha in glossary_terms %}
      <div id=section_{{ alpha[0][0] }}>
        {% for term in alpha %}
        <div class=glossary-term id=glossary__{{ term }}>
        {% include 'modules/glossary/terms/{}.html'.format(term) %}
        {% if term in advanced_glossary_terms %}
        <div class=advanced-term></div>
        {% endif %}
        </div>
        {% endfor %}
      </div>
      {% endfor %}
    {% endblock %}
    </div>
  </div>
{% endblock %}
{% block bodyjs %}
{{ super() }}
<script src={{ url_for('webdice.static', filename='js/webdice_glossary.js') }}></script>
{% endblock %}

webdice_web/templates/modules/glossary/static_page.html
{% extends 'modules/glossary/index.html' %}
{% block glossary_list %}
  {% include 'modules/glossary/terms/{}.html'.format(term) %}
  {% if term in advanced_glossary_terms %}
  {% include 'modules/glossary/terms/advanced/{}.html'.format(term) %}
  {% endif %}
{% endblock %}

webdice_web/templates/modules/glossary/terms/advanced/abatement.html
<p>The abatement cost, $$\Lambda(t),$$ is the fraction of output spent on
  limiting emissions based on the specifications of a given climate policy.
  There are three components to abatement costs: the emissions control rate,
  $\mu(t)$, the participation fraction, $\varphi(t)$, and the cost of
  replacing all fossil fuels with carbon-free energy (the backstop
  technology), $\theta_{1}(t)$. Abatement costs are the product of these
  three components:</p>
\[
\Lambda(t)=\theta_{1}(t)\varphi(t)^{1-\theta_{2}}\mu(t)^{\theta_{2}}.
\]

webdice_web/templates/modules/glossary/terms/advanced/clean_energy.html
<!-- TODO: Technical description of clean energy costs -->
<p>technical description</p>

webdice_web/templates/modules/glossary/terms/carbon_tax.html
<h3>Carbon tax</h3>
<p>A carbon tax is a tax on emissions. Without a tax or some other price on
  emission, people do not consider the full consequences of their actions.
  They can emit CO<sub>2</sub> without considering that this harms others.
  Economists call this a market failure: the price of fossil fuel energy
  does not represent the true price, unlike with most other products in the
  economy. A a result, people use too much fossil fuel energy.</p>
<p>A carbon tax fixes this problem by enforcing people to consider the full
  costs of fossil fuel energy, including the harms that using fuel energy
  will cause due to climate change. A carbon tax is thought by many to be
  the most efficient method of controlling emissions.</p>
<p>There are two ways in the model to impose a carbon tax. The first is
  to choose a carbon tax explicitly through the
  <a href="#glossary__simulated_carbon_tax">simulated carbon tax
    option</a>. The second is to choose the optimization
  option. If you choose optimization, the computer calculates an emissions
  path that maximizes the objective function and then determines the
  carbon tax that is necessary to achieve that path.
  <a class=link-to-advanced-glossary
    href={{ url_for('webdice.glossary_term', term='carbon_tax') }}>more
  </a>
</p>

webdice_web/templates/modules/glossary/terms/clean_energy.html
<h3>Clean energy costs</h3>
<p>To reduce emissions, we have to replace fossil fuels with other sources
  of energy that do not produce emissions, such as solar or wind power.
  Replacing fossil fuels with clean energy will cost money, and tis price
  determines how much it will cost to stop climate change. The model
  estimates the cost of replacing a portion (or all_ of the fossil fuel
  system starting with an estimate of the cost of replacing the entire
  fossil fuel system with clean energy. This price is set a relatively high
  level for 2005 of USD1,260/ton C or equivalently, USD344/ton CO<sub>2</sub>.
  The price is assumed to go down over time as our technology improves.</p>
<p>You can choose how fast the price of clean energy goes down. The initial
  rate is 5% per year so that if clean energy costs USD1,000/ton C this year,
  it will cost USD950/ton C next year. If you are optimistic about future
  technology, you can increase the rate at which the price goes down by
  <!-- TODO: Get min and max values -->
  moving the slider to  _ _ _ and if you are pessimistic, you can reduce
  the rate, all the way down to _ _ _.
  <!--<a class=link-to-advanced-glossary
     href={{ url_for('webdice.glossary_term', term='clean_energy_costs') }}>more
  </a>-->
</p>

webdice_web/templates/modules/glossary/terms/damages.html
<h3>Damages from climate change</h3>
<p>The results in webDICE, with the exception of the
  <a href="#glossary__social_cost_of_carbon">
    social costs of carbon</a> do not depend on the discount rate. Instead,
  webDICE calculates the change in consumption in each period, translates
  that to a change in utility via the
  <a href="#glossary__utility">utility function</a> and sums up the changes
  in utility.</p>
<p>The ‘pure rate of time preference’ is subtly different than the
  discount rate. The discount rate applies to money or, in webDICE,
  things money can buy like consumption. It is like the interest rate
  you get when you put money in the bank or that you pay when you
  borrow money. The pure rate of time preference is part of the process
  of adding up the utility of people to determine how well society is
  doing. It applies directly to utility, not to money. It is a way of
  computing the present value of the utility of people who live in the
  future.
  <a class=link-to-advanced-glossary
     href={{ url_for('webdice.glossary_term', term='damages') }}>more
  </a>
</p>

webdice_web/templates/modules/glossary/terms/energy_intensity.html
<h3>Energy intensity/carbon intensity</h3>
<p>Economic activity, such as heating, transportation and manufacturing,
  requires energy. The major source of energy in modern economics is from
  fossil fuels, coal, petroleum and natural gas. This means that economic
  activity produces emissions, called ‘industrial emissions’ in webDICE.
  The richer we are, the greater the emissions, and conversely, the poorer
  we are, the lower the emissions.</p>
<p>Over time, the economy has gotten more efficient: we are able to produce
  the same amount using less energy. For example, gas mileage for vehicles
  has gone up over time, so that we are able to drive the same distance
  using less energy and producing fewer emissions. webDICE includes this
  effect by estimating the ‘energy intensity’ of the economy: how much
  output we can produce with a given amount of energy. We can estimate our
  current energy intensity from data and we know that energy intensity
  has declined over time. webDICE assumes that this trend continues,
  resulting in a gradual reduction in emissions per unit of output
  (although if economic activity grows faster than energy intensity
  goes down, emissions can overall increase).</p>
<p>While webDICE assumes that energy intensity goes down over time,
  the rate of decline slows down. That is, efficiency improvements get
  harder over time. You can set to rate of decline of energy intensity
  (or equivalently, the rate of efficiency improvements in our use of
  energy). If you set the value at zero, our energy intensity does not
  go down over time. We never improve our efficiency. As you increase
  the value, we improve our efficiency more quickly and we become less
  energy intensive. The following figure illustrates how carbon
  intensity evolves for choice of this parameter:</p>
  <figure>
    <img src="{{ url_for('webdice.static', filename='images/glossary/sig.png') }}" alt>
    <figcaption>Figure 3: Pathway of carbon intensity for user-choice of
      decarbonization rate</figcaption>
  </figure>
<p>Cumulative industrial emissions are limited by the total available
  amount of fossil fuels. This cap is currently set at 6,000 gigatons
  of carbon dioxide, but users can increase this amount.
  <a class=link-to-advanced-glossary
     href={{ url_for('webdice.glossary_term', term='energy_intensity') }}>more
  </a>
</p>

webdice_web/templates/modules/glossary/terms/social_cost_of_carbon.html
<h3>Social cost of carbon</h3>
<p>The social cost of carbon (SCC) is a commonly cited metric which
  estimates the increase in harms from additional emissions. To estimate
  this, webDICE runs the model once (under your chosen parameters) and
  then again with one additional ton of CO<sub>2</sub> and calculates the
  difference in the two cases. The increase in harms from the additional
  ton is the social cost of carbon. U.S. government agencies are
  required to use this metric in cost-benefit evaluation of new programs.
  Although the commonly used term is social cost of carbon, it is
  standard to report the value in dollars per ton of carbon dioxide,
  not carbon. webDICE follows this practice.</p>
<p>webDICE calculates the social cost of carbon for each period by
  sequentially adding the additional ton in each period. For example,
  the social cost of carbon in 2055 is the increase in harms one an
  additional ton of CO<sub>2</sub> is added in the year 2055.
  <a class=link-to-advanced-glossary
     href={{ url_for('webdice.glossary_term', term='social_cost_of_carbon') }}>more
  </a>
</p>